{% set name = "topfarm" %}
{% set version = "2.6.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e70611bc4df9883469c82bcf7ce89bd9bf6d1edf1141c2c697b32fca78c6e79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatch-vcs
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - numpy-financial
    - openmdao <3.40
    - pydoe2
    - pydoe3 >=1.0.4,<2
    - scipy
    - scikit-learn
    - shapely >=2.0.6,<3
    - jupyterlab
    - py-wake >=2.6.5

test:
  imports:
    - topfarm
#  commands:
#    - pip check # fails due to git-lfs not available on conda
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/topfarm2
  summary: Topfarm - Wind farm optimization using OpenMDAO
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neda-dtu
    - mifm
    - madsmpedersen
    - simutisernestas
