{% set name = "topfarm" %}
{% set version = "2.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 909b5723e5f3e6fc79be34165a5e7f9ded37590aa3e94c0ce51f012f92808dff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - hatch-vcs
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - numpy-financial
    - openmdao
    - pydoe2
    - pydoe3 >=1.0.4,<2
    - scipy
    - scikit-learn
    - shapely >=2.0.6,<3
    - jupyterlab
    - py-wake >=2.6.5

test:
  imports:
    - topfarm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.windenergy.dtu.dk/TOPFARM/topfarm2
  summary: Topfarm - Wind farm optimization using OpenMDAO
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neda-dtu
    - mifm
    - madsmpedersen
    - simutisernestas
